import type { ComponentManifest } from '../meta/manifest-schema';

export default {
  type: 'Gallery',
  category: 'Media',
  label: 'Thư viện ảnh',
  description: 'Lưới hoặc băng ảnh, mỗi ảnh có chú thích tuỳ chọn.',
  icon: 'Images',
  acceptsChildren: false,
  allowedChildTypes: null,
  allowedInPageKinds: ['Composable'],
  maxPerPage: null,
  aiSummary: 'Thư viện {{_itemCount}} ảnh',
  since: '1.0.0',

  variants: [
    {
      key: 'Gallery01',
      label: 'Lưới 3 cột',
      preview: 'gallery/g01.webp',
      usesProps: ['heading', 'items', 'columns'],
      requiresProps: ['items'],
      since: '1.0.0',
    },
    {
      key: 'Gallery02',
      label: 'Băng cuộn ngang',
      preview: 'gallery/g02.webp',
      usesProps: ['heading', 'items'],
      requiresProps: ['items'],
      since: '1.0.0',
    },
  ],

  props: {
    heading: {
      kind: 'text',
      label: 'Tiêu đề',
      maxLength: 120,
      multiline: false,
      group: 'Nội dung',
      order: 1,
      editableInSystemPage: false,
      since: '1.0.0',
    },
    items: {
      kind: 'list',
      label: 'Danh sách ảnh',
      itemLabel: 'Ảnh',
      minItems: 1,
      maxItems: 24,
      group: 'Nội dung',
      order: 2,
      editableInSystemPage: false,
      since: '1.0.0',
      itemProps: {
        image: {
          kind: 'image',
          label: 'Ảnh',
          preset: '800x800,cover',
          allowFocalPoint: true,
          group: '_',
          order: 1,
          editableInSystemPage: false,
          since: '1.0.0',
        },
        caption: {
          kind: 'text',
          label: 'Chú thích',
          maxLength: 120,
          multiline: false,
          group: '_',
          order: 2,
          editableInSystemPage: false,
          since: '1.0.0',
        },
      },
    },
    columns: {
      kind: 'number',
      label: 'Số cột',
      min: 2,
      max: 4,
      step: 1,
      default: 3,
      group: 'Hiển thị',
      order: 1,
      editableInSystemPage: false,
      since: '1.0.0',
    },
  },
} satisfies ComponentManifest;
