import type { ComponentManifest } from '../meta/manifest-schema';

export default {
  type: 'Hero',
  category: 'Content',
  label: 'Banner đầu trang',
  description: 'Khối lớn đầu trang với tiêu đề, mô tả ngắn và nút hành động.',
  icon: 'Image',
  acceptsChildren: false,
  allowedChildTypes: null,
  allowedInPageKinds: ['Composable'],
  maxPerPage: 1,
  aiSummary: 'Banner: "{{title}}"',
  since: '1.0.0',

  variants: [
    {
      key: 'Hero01',
      label: 'Ảnh nền toàn khối',
      preview: 'hero/hero01.webp',
      usesProps: ['title', 'subtitle', 'image', 'overlayOpacity', 'align', 'cta'],
      requiresProps: ['title', 'image'],
      since: '1.0.0',
    },
    {
      key: 'Hero02',
      label: 'Chia đôi: chữ trái, ảnh phải',
      preview: 'hero/hero02.webp',
      usesProps: ['title', 'subtitle', 'image', 'align', 'cta'],
      requiresProps: ['title'],
      since: '1.0.0',
    },
  ],

  props: {
    title: {
      kind: 'text',
      label: 'Tiêu đề',
      maxLength: 120,
      multiline: false,
      group: 'Nội dung',
      order: 1,
      editableInSystemPage: false,
      since: '1.0.0',
    },
    subtitle: {
      kind: 'richText',
      label: 'Mô tả ngắn',
      profile: 'inline',
      maxLength: 300,
      group: 'Nội dung',
      order: 2,
      editableInSystemPage: false,
      since: '1.0.0',
    },
    image: {
      kind: 'image',
      label: 'Ảnh',
      preset: '1600x900,cover',
      allowFocalPoint: true,
      group: 'Nội dung',
      order: 3,
      editableInSystemPage: false,
      since: '1.0.0',
    },
    cta: {
      kind: 'group',
      label: 'Nút hành động',
      group: 'Nội dung',
      order: 4,
      editableInSystemPage: false,
      since: '1.0.0',
      props: {
        label: {
          kind: 'text',
          label: 'Chữ trên nút',
          maxLength: 40,
          group: '_',
          order: 1,
          editableInSystemPage: false,
          since: '1.0.0',
        },
        target: {
          kind: 'link',
          label: 'Liên kết tới',
          allowKinds: ['page', 'systemPage', 'external', 'anchor'],
          group: '_',
          order: 2,
          editableInSystemPage: false,
          since: '1.0.0',
        },
      },
    },
    overlayOpacity: {
      kind: 'number',
      label: 'Độ mờ lớp phủ',
      min: 0,
      max: 80,
      step: 5,
      unit: '%',
      default: 35,
      group: 'Hiển thị',
      order: 1,
      editableInSystemPage: false,
      since: '1.0.0',
    },
    align: {
      kind: 'select',
      label: 'Căn chữ',
      default: 'center',
      options: [
        { value: 'left', label: 'Trái' },
        { value: 'center', label: 'Giữa' },
      ],
      group: 'Hiển thị',
      order: 2,
      editableInSystemPage: false,
      since: '1.0.0',
    },
  },
} satisfies ComponentManifest;
